# SPDX-FileCopyrightText: Contributors to the Cable Thermal Model project
#
# SPDX-License-Identifier: MPL-2.0

# Disable rules for TODOs and variable naming
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S117
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S1135

sonar.projectKey=alliander-opensource_cable-thermal-model
sonar.organization=alliander-opensource
sonar.sources=cable_thermal_model

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=\
    **/tests/**, \
    **/docs/**, \
