# SPDX-FileCopyrightText: Contributors to the Cable Thermal Model project
#
# SPDX-License-Identifier: MPL-2.0

from typing import Generic, TypeVar

from pydantic import BaseModel, ConfigDict, Field

from cable_thermal_model.model.schemas.state_schemas import StateAir, StateSoil, StateT

ModelRunOptionsT = TypeVar("ModelRunOptionsT", bound="ModelRunOptions")


class ModelRunOptions(BaseModel, Generic[StateT]):
    """Base run-time options shared by all model types."""

    model_config = ConfigDict(extra="forbid")

    temperature_dependent_electric_resistance: bool = Field(
        default=True,
        description="Whether to let the electric resistance of materials be temperature dependent.",
    )
    ac_current: bool = Field(
        default=True,
        description=(
            "Whether to use an AC current. If True, the model will account for AC conductor "
            "(skin effect, proximity effect) resistance, screen losses and dielectric losses."
        ),
    )
    neglect_dielectric_loss: bool = Field(
        default=False,
        description=(
            "Whether to neglect dielectric loss in the model. "
            "If True, the model will not account for the heat generated by dielectric losses in the cable insulation."
        ),
    )


class ModelSoilRunOptions(ModelRunOptions[StateSoil]):
    """Run-time options for the soil model, extending ModelRunOptions with soil-drying support."""

    soil_drying: bool = Field(
        default=False,
        description="Whether to let soil dry out around cables due to cable heating.",
    )


class ModelAirRunOptions(ModelRunOptions[StateAir]):
    """Run-time options for the air model; no additional options beyond the base class."""

    pass
